dataset:
  path: /home/lucianolorenti/transformed
  name: 'basic'

model:
  path: /home/lucianolorenti/models
  name: 'cnn_residual2'
  params:
    n_residuaks: 3
    

train:
  batch_size: 1024
  epochs: 50
