dataset:
  path: /home/lucianolorenti/transformed
  name: 'basic'

model:
  path: /home/lucianolorenti/models
  name: 'cnn_inception2'
  params:
    n_filters: 22
    sizes: [10, 20, 30]

train:
  batch_size: 1024
  epochs: 25
