dataset:
  path: /home/luciano/speech_2

model:
  path: /home/luciano/model
  name: 'cnn_residual2'
  params:
    n_residuals: 3
    n_filters: 19
    

train:
  batch_size: 64
  epochs: 27

output_path: /home/luciano/model
