model:
  name: 'cnn_visiontransformer'
  params:
    learning_rate: 0.001
    n_dense_layer: 1
    num_heads: 3
    transformer_layers: 4
    projection_dim: 20
    patch_x: 20
    patch_y: 40
  windowed: False

train:
  batch_size: 64
  epochs: 27
  reduce_on_plateau: True
